---
- name: This is a hello-world example
  hosts: appserver
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: hello worldn
        dest: ~/Documents/testfile.txt
    - name: Testing
      ansible.builtin.debug:
        msg: "test"

    - name: Looping and printing
      debug: msg="{{item.path}}"
      loop:
        - path: test1
        - path: test2
    
